name: Playwright Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    paths:
      - "packages/npm-packages/runtime/**/*.rb"
      - "examples/**/*.spec.js"
      - ".github/workflows/playwright.yml"
      - "playwright.config.js"

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Get installed Playwright version
        id: playwright-version
        run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./node_modules/@playwright/test/package.json').version)")" >> $GITHUB_ENV

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}-${{ runner.os }}

      - name: Install Playwright Browsers (Chromium only)
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install chromium --with-deps

      - name: Cache runtime node_modules
        uses: actions/cache@v4
        with:
          path: packages/npm-packages/runtime/node_modules
          key: runtime-node-modules-${{ hashFiles('packages/npm-packages/runtime/package-lock.json') }}

      - name: Install runtime dependencies
        run: |
          cd packages/npm-packages/runtime
          npm ci

      - name: Build runtime package
        run: |
          cd packages/npm-packages/runtime
          npm run build:dev

      - name: Run Playwright tests
        run: npm run test

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 30
